import { createGhosts } from './ghost.js';
import { createMaze } from './create_maze.js';
import { Pacman } from './pacman.js';

export const maze = [
  'WWWWWWWWWWWWWWWWWWWWWWW',
  'WPPPWPPPPPPPPPPPPPWPPPW',
  'WPWPWPWWWWWPWWWWWPWPWPW',
  'WPPPPPPPWPPPPPWPPPPPPPW',
  'WWWPWPWPWPWWWPWPWPWPWWW',
  'WPPPWPWPWPW WPWPWPWPPPW',
  'WPWPWPWPWPWWWPWPWPWPWPW',
  'WPPPWPWPPPPPPPPPWPWPPPW',
  'WWWWWPWPWWWWWWWPWPWWWWW',
  'WPPPPPWPPPPPPPPPWPPPPPW',
  'WPWWWWWPGGGTGGGPWWWWWPW',
  'OPPPPPPPG     GPPPPPPPO',
  'WPWWWWWPGGGGGGGPWWWWWPW',
  'WPPPPPWPPPPPPPPPWPPPPPW',
  'WWWWWPWPWWWWWWWPWPWWWWW',
  'WPPPWPWPPPPPPPPPWPWPPPW',
  'WPWPWPWPWPWWWPWPWPWPWPW',
  'WPPPWPWPWPW WPWPWPWPPPW',
  'WWWPWPWPWPWWWPWPWPWPWWW',
  'WPPPPPPPWPPPPPWPPPPPPPW',
  'WPWPWPWWWWWPWWWWWPWPWPW',
  'WPPPWPPPPPPPPPPPPPWPPPW',
  'WWWWWWWWWWWWWWWWWWWWWWW',
];

export const tileClasses = {
  W: 'wall',
  P: 'path',
  G: 'ghost-pen',
  T: 'gate',
  O: 'warp',
};

document.addEventListener('DOMContentLoaded', () => {
  createMaze();
  window.pacman = new Pacman();
  window.ghosts = createGhosts();
});
